### ISSUE TITLE
Dynamic organization settings example?

### ISSUE THREAD

**Issue by garnertb** [microsoft/opensource-management-portal#496]
I'm trying to move from a static organization configuration to a dynamic one.  I initially assumed I could load the static configuration in the `metadata` column of `organizationsettings` and everything would work the same, but that isn't the case.  There are variations between the implementation and expectations of dynamic settings and static settings, which are challenging to understand without documentation or examples.  

Any chance you could add an example of what a valid dynamic organization looks like?

Example static config from [static orgs documentation](https://github.com/microsoft/opensource-management-portal/blob/main/docs/configuration.md#static-orgs): 
```json
{
    "name": "ContosoDev",
    "id": 20195765,
    "type": "public",
    "ownerToken": "keyvault://portalppe.vault.azure.net/secrets/dev-github-org-contosodev-repos-token",
    "description": "Contoso Public Development - Cloud",
    "teamAllMembers": "2063735",
    "teamPortalSudoers": "2063734",
    "preventLargeTeamPermissions": true,
    "teamAllReposRead": "2280089",
    "teamAllReposWrite": "2148455",
    "templates": ["mit", "microsoft.docs", "dnfmit", "dnfmit.docs", "other"]
  },
```

Here are examples I've found so far:

1. In the example below, note the `organizationsettings_organizationid` index, which uses the `organizationid` property which I assume should map to the `id` property in the static schema above. 
```
postgres=# \d organizationsettings
         Table "public.organizationsettings"
   Column   | Type  | Collation | Nullable | Default
------------+-------+-----------+----------+---------
 entitytype | text  |           | not null |
 entityid   | text  |           | not null |
 metadata   | jsonb |           |          |
Indexes:
    "organizationsettings_pkey" PRIMARY KEY, btree (entitytype, entityid)
    "organizationsettings_active" btree ((metadata ->> 'active'::text))
    "organizationsettings_organizationid" btree ((metadata ->> 'organizationid'::text))
```

2. After copying over setting that work in a static file the app will crash.

Example metadata payload: 
```
{"name":"a Sample","type":["public","private","internal"],"active":true,"description":"This is a sample org","installations":[123]}
```

App crashes due to hardcodes lookup of `organizationName` here: https://github.com/microsoft/opensource-management-portal/blob/1339b4442323e3dbc138f0c2a83b75fbed65a46e/business/operations/index.ts#L237

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Operations.get organizationNames [as organizationNames] (/Users/tyler/projects/github-portal/dist/business/operations/index.js:135:60)
    at Operations.get organizations [as organizations] (/Users/tyler/projects/github-portal/dist/business/operations/index.js:216:32)
    at Operations.getOrganizationIds (/Users/tyler/projects/github-portal/dist/business/operations/index.js:152:40)
    at Operations.initialize (/Users/tyler/projects/github-portal/dist/business/operations/index.js:116:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async initializeAsync (/Users/tyler/projects/github-portal/dist/middleware/initialize.js:215:9)
    at async initialize (/Users/tyler/projects/github-portal/dist/middleware/initialize.js:332:13)
    at async startup (/Users/tyler/projects/github-portal/dist/app.js:45:13)
```

3. There also seem to be properties that only work in the dynamic configuration and not the static configuration, like `installations`.

## Differences
|Static Setting|Dynamic Setting|Notes|
|:-:|:-:|:-:|
|id|organizationid||
|name|organizationname||
|locked|features["locked"]| needs to be added to the "features" array as a string|
|-|updated|Not used in static settings, needed for dynamic restart logic|

### Dynamic Settings
**Note**: Properties are all lowercased further on in code, but this gives us an idea of what the metadat object should look like.  

```typescript
const Field: IOrganizationSettingProperties = {
  // organizationId: 'organizationId',
  setupByCorporateDisplayName: 'setupByCorporateDisplayName',
  setupByCorporateId: 'setupByCorporateId',
  setupByCorporateUsername: 'setupByCorporateUsername',
  setupDate: 'setupDate',
  active: 'active',
  updated: 'updated',
  organizationName: 'organizationName',
  portalDescription: 'portalDescription',
  operationsNotes: 'operationsNotes',
  installations: 'installations',
  features: 'features',
  properties: 'properties',
  specialTeams: 'specialTeams',
  templates: 'templates',
  legalEntities: 'legalEntities',
}
```

**Comment by garnertb** [comment]
Documented a lot of the differences here: https://github.com/microsoft/opensource-management-portal/pull/527
